"""Figure 1: survival curves (RFS and OS) from the canonical model.

Only Figure 1 lives here. Figure 2 (CEAC) is generated by gen_psa_output.py,
Figure 3 (tornado) by gen_tornado.py, Figure 4 (price-ICER) by gen_fig4.py, and
Figures S6/S7 by gen_fig_s6_s7_v2.py.
"""
import contextlib
import io

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from model import ModelParams
from rerun_primary import CEAModelV2

plt.rcParams.update({
    "font.family": "sans-serif", "font.size": 11,
    "axes.titlesize": 13, "axes.labelsize": 12,
    "figure.dpi": 300, "savefig.dpi": 300,
    "savefig.bbox": "tight", "savefig.pad_inches": 0.1,
})
C = {"combo": "#2166ac", "pembro": "#b2182b"}


def plot_survival():
    params = ModelParams(constraint_general_pop=True)
    model = CEAModelV2(params)
    with contextlib.redirect_stdout(io.StringIO()):
        sur = model._survival()
    t = model.t

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4.5))
    for arm_name in ["combo", "pembro"]:
        label = "Intismeran + Pembro" if arm_name == "combo" else "Pembrolizumab"
        ax1.plot(t, sur[f"rfs_{arm_name}"], color=C[arm_name], label=label)
        ax2.plot(t, sur[f"os_{arm_name}"], color=C[arm_name], label=label)

    # 5-year KEYNOTE-942 landmarks
    ax1.plot(5, 0.688, "o", color=C["combo"], ms=6)
    ax1.plot(5, 0.491, "o", color=C["pembro"], ms=6)
    ax2.plot(5, 0.922, "o", color=C["combo"], ms=6)
    ax2.plot(5, 0.713, "o", color=C["pembro"], ms=6)

    for ax, title in [(ax1, "Recurrence-Free Survival"), (ax2, "Overall Survival")]:
        ax.set_xlabel("Years"); ax.set_ylabel("Survival Probability")
        ax.set_title(title); ax.legend(fontsize=9)
        ax.set_xlim(0, 40); ax.set_ylim(0, 1); ax.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig("fig1_survival.png", dpi=300)
    plt.close()
    print("OK fig1_survival.png")


if __name__ == "__main__":
    plot_survival()
